language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

dist: xenial

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist
  - cd $TRAVIS_BUILD_DIR

script:
  - composer lint
  - composer install-cs-fixer
  - composer check-style
  - composer phpstan
  - composer test-coverage

